package com.imminentmeals.android.base;

import javax.inject.Singleton;

import org.holoeverywhere.app.Application;
import org.holoeverywhere.preference.PreferenceManagerHelper;
import org.holoeverywhere.preference.SharedPreferences;

import android.accounts.AccountManager;
import android.annotation.SuppressLint;
import android.content.Context;
import android.os.StrictMode;
import android.preference.PreferenceManager;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.imminentmeals.android.base.utilities.GateKeeper;
import com.imminentmeals.android.base.utilities.ObjectGraph.ObjectGraphApplication;
import com.squareup.otto.Bus;

import dagger.Module;
import dagger.ObjectGraph;
import dagger.Provides;

/**
 * <p>Enables {@link StrictMode} during debugging, creates the {@linkplain ObjectGraph object graph} for dependency
 * injection, and registers {@linkplain Application#ActivityLifecycleCallbacks Activity lifecycle callbacks}.
 * @author Dandré Allison
 */
public class BaseAndroidLibraryApplication extends Application implements ObjectGraphApplication {

    @SuppressLint("NewApi")
    @Override
    public void onCreate() {
        if (BuildConfig.DEBUG && GateKeeper.hasGingerbread())
            StrictMode.enableDefaults();
        super.onCreate();

        // Creates the dependency injection object graph
        _object_graph = ObjectGraph.create(new BaseAndroidLibraryModule(this));

        // TODO: setDefaultPreferences here
        // TODO: registerActivityLifecycleCallbacks
    }

    @Override
    public ObjectGraph objectGraph() {
        return _object_graph;
    }

    /**
     * <p>Module class that defines injection entry points that aren't defined in the
     * AndroidManifest (like Fragment and non-Android classes). This allows Dagger to inject
     * their dependencies. It also {@link Provides} dependencies that can be injected at entry
     * points.</p>
     *
     * @author Dandré Allison
     */
    @Module(
            entryPoints = {
            },
            includes = {
                    // Module generated by dagger-androidmanifest-plugin
                    ManifestModule.class
            }
    )
    /* package */static class BaseAndroidLibraryModule {

        /**
         * <p>Constructs the module using the {@link Context} to retrieve the application context
         * from which to retrieve context-dependent dependencies.</p>
         * @param context The context from which to retrieve the application context
         */
        public BaseAndroidLibraryModule(Context context) {
            _context = context.getApplicationContext();
        }

        @Provides @Singleton Bus provideBus() {
            return new Bus();
        }

        @Provides @Singleton Gson provideGson() {
            return new GsonBuilder().create();
        }

        @Provides @Singleton SharedPreferences provideSharedPreferences() {
            return PreferenceManagerHelper.getDefaultSharedPreferences(_context);
        }

        @Provides @Singleton AccountManager provideAccountManager() {
            return AccountManager.get(_context);
        }

        @Provides Context provideContext() {
            return _context;
        }

        /** The context in which the app is running */
        private final Context _context;
    }

    /** Application's object graph for handling dependency injection */
    private ObjectGraph _object_graph;
}
